# https://travis-ci.org/tornadoweb/tornado
language: python
python:
    - 3.4
    - 3.5

env:
    - DEV=true
    - DEV=false

install:
    - pip install -r requirements.txt

script:
    - echo "No Test for Now"
    - if [[ $TRAVIS_PYTHON_VERSION == '3.5' && $DEPS == true ]]; then cd ../docs && mkdir sphinx-doctest-out && sphinx-build -E -n -b doctest . sphinx-out; fi

sudo: false
